/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sms.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
        //initComponents();
        loadStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSlider1 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextArea1);

        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(this::jSlider1StateChanged);

        jLabel10.setText("Slider:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        jTextField1.setText("Type student full names");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 270, 30));

        jLabel2.setText("Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        jTextField2.setText("type  student  email");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 270, 30));

        jLabel3.setText("Course:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose course", "Java programming", "Computer graphic", "Data structure", "c++ programing" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 270, 30));

        jLabel4.setText("Marks:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        jTextField3.setText("Student marks");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 270, 27));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Complete the students information");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 400, 30));

        jButton1.setBackground(new java.awt.Color(40, 167, 69));
        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 193, 7));
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jButton3.setBackground(new java.awt.Color(220, 53, 69));
        jButton3.setText("Delete");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 64, -1));

        jButton6.setBackground(new java.awt.Color(23, 162, 184));
        jButton6.setText("View status");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jScrollPane2.setViewportView(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Welcome to Dashboard status!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "search by", "id", "name", "email", "marks", "course" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 123, 200));
        jButton4.setText("Search");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton7.setBackground(new java.awt.Color(23, 162, 184));
        jButton7.setText("View All");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton5.setBackground(new java.awt.Color(108, 117, 122));
        jButton5.setText("Clear");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jLabel8.setText("Sort by:");

        buttonGroup2.add(jCheckBox1);
        jCheckBox1.setText("Id");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        buttonGroup2.add(jCheckBox2);
        jCheckBox2.setText("Name");
        jCheckBox2.addActionListener(this::jCheckBox2ActionPerformed);

        buttonGroup2.add(jCheckBox3);
        jCheckBox3.setText("Grade");
        jCheckBox3.addActionListener(this::jCheckBox3ActionPerformed);

        jLabel7.setText("Filters:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Passed");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Failed");
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Graduated");
        jRadioButton3.addActionListener(this::jRadioButton3ActionPerformed);

        jLabel6.setText("Student Records");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox3))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2)
                                        .addGap(27, 27, 27)
                                        .addComponent(jRadioButton3))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("STUDENT MANAGEMNET SYSTEM (SMS)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 200));

        jMenu1.setText("File");
        jMenu1.addActionListener(this::jMenu1ActionPerformed);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Add");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("student");

        jMenuItem4.setText("Add");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Update");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Delete");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu10.setText("help");

        jMenuItem1.setText("About");
        jMenu10.add(jMenuItem1);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(486, 486, 486)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 584, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(255, 255, 255))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //here
    try {
        // 1. Get data from fields
        //String idStr = jTextField3.getText().trim();
        String rawName = jTextField1.getText().trim();
        String email = jTextField2.getText().trim();
        String course = jComboBox1.getSelectedItem().toString();
        String marksStr = jTextField3.getText().trim();

        // 2. Validation: Check if empty
        if (rawName.isEmpty() || email.isEmpty() || marksStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return;
        }

        // 3. String Manipulation: Title Case (Lab Requirement)
        String formattedName = "";
        String[] words = rawName.split("\\s+");
        for (String word : words) {
            if (word.length() > 0) {
                formattedName += word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase() + " ";
            }
        }
        formattedName = formattedName.trim();

        // 4. Email Validation
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Invalid Email Format!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 5. Numeric Validation
        //int id = Integer.parseInt(idStr);
        int marks = Integer.parseInt(marksStr);
        if (marks < 0 || marks > 100) {
            JOptionPane.showMessageDialog(this, "Marks must be between 0 and 100");
            return;
        }

        // 6. Database Insertion
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "INSERT INTO students (name, email, course, marks) VALUES ( ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        //pst.setInt(1, id);
        pst.setString(1, formattedName);
        pst.setString(2, email);
        pst.setString(3, course);
        pst.setInt(4, marks);

        pst.executeUpdate();
        
        // 7. Success!
        JOptionPane.showMessageDialog(this, "Student Added Successfully: " + formattedName);
        
        // Refresh the table and clear fields
         loadStudents(); 
        clearFields();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID and Marks must be numbers!", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error (Check if ID already exists): " + e.getMessage());
    }      
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    try {
        // 1. Get data from fields
        //String idStr = jTextField3.getText().trim();
        String rawName = jTextField1.getText().trim();
        String email = jTextField2.getText().trim();
        String course = jComboBox1.getSelectedItem().toString();
        String marksStr = jTextField3.getText().trim();

        // 2. Validation: Check if empty
        if (rawName.isEmpty() || email.isEmpty() || marksStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return;
        }

        // 3. String Manipulation: Title Case (Lab Requirement)
        String formattedName = "";
        String[] words = rawName.split("\\s+");
        for (String word : words) {
            if (word.length() > 0) {
                formattedName += word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase() + " ";
            }
        }
        formattedName = formattedName.trim();

        // 4. Email Validation
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Invalid Email Format!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 5. Numeric Validation
        //int id = Integer.parseInt(idStr);
        int marks = Integer.parseInt(marksStr);
        if (marks < 0 || marks > 100) {
            JOptionPane.showMessageDialog(this, "Marks must be between 0 and 100");
            return;
        }

        // 6. Database Insertion
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "INSERT INTO students (name, email, course, marks) VALUES ( ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        //pst.setInt(1, id);
        pst.setString(1, formattedName);
        pst.setString(2, email);
        pst.setString(3, course);
        pst.setInt(4, marks);

        pst.executeUpdate();
        
        // 7. Success!
        JOptionPane.showMessageDialog(this, "Student Added Successfully: " + formattedName);
        
        // Refresh the table and clear fields
         loadStudents(); 
        clearFields();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID and Marks must be numbers!", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error (Check if ID already exists): " + e.getMessage());
    }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    String idToUpdate = JOptionPane.showInputDialog(this, "Enter the Student ID you want to update:");
    
    // If user clicks cancel or leaves it blank, stop
    if (idToUpdate == null || idToUpdate.trim().isEmpty()) {
        return;
    }

    // 2. Ask for the New Marks
    String newMarksStr = JOptionPane.showInputDialog(this, "Enter the new marks for Student ID " + idToUpdate + ":");
    
    if (newMarksStr == null || newMarksStr.trim().isEmpty()) {
        return;
    }

    try {
        // 3. Convert inputs to numbers
        int id = Integer.parseInt(idToUpdate.trim());
        int marks = Integer.parseInt(newMarksStr.trim());

        // 4. Validate marks range
        if (marks < 0 || marks > 100) {
            JOptionPane.showMessageDialog(this, "Marks must be between 0 and 100!");
            return;
        }

        // 5. Database Update
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "UPDATE students SET marks = ? WHERE id = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setInt(1, marks);
        pst.setInt(2, id);

        int rowsAffected = pst.executeUpdate();

        // 6. Check if the ID actually existed
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Update Successful for Student ID: " + id);
            loadStudents(); // Refresh the list to show new marks
        } else {
            JOptionPane.showMessageDialog(this, "Student ID " + id + " not found in database.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numbers for ID and Marks!", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idToDelete = JOptionPane.showInputDialog(this, "Enter Student ID to Delete:");
    
    if (idToDelete == null || idToDelete.isEmpty()) return;

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete ID: " + idToDelete + "?", "Confirm", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
            String sql = "DELETE FROM students WHERE id = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(idToDelete));
            
            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Student Deleted!");
                //loadStudents(); // Refresh display
            } else {
                JOptionPane.showMessageDialog(this, "ID not found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// 1. Ask for the Student ID
    String idToUpdate = JOptionPane.showInputDialog(this, "Enter the Student ID you want to update:");
    
    // If user clicks cancel or leaves it blank, stop
    if (idToUpdate == null || idToUpdate.trim().isEmpty()) {
        return;
    }

    // 2. Ask for the New Marks
    String newMarksStr = JOptionPane.showInputDialog(this, "Enter the new marks for Student ID " + idToUpdate + ":");
    
    if (newMarksStr == null || newMarksStr.trim().isEmpty()) {
        return;
    }

    try {
        // 3. Convert inputs to numbers
        int id = Integer.parseInt(idToUpdate.trim());
        int marks = Integer.parseInt(newMarksStr.trim());

        // 4. Validate marks range
        if (marks < 0 || marks > 100) {
            JOptionPane.showMessageDialog(this, "Marks must be between 0 and 100!");
            return;
        }

        // 5. Database Update
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "UPDATE students SET marks = ? WHERE id = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setInt(1, marks);
        pst.setInt(2, id);

        int rowsAffected = pst.executeUpdate();

        // 6. Check if the ID actually existed
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Update Successful for Student ID: " + id);
            loadStudents(); // Refresh the list to show new marks
        } else {
            JOptionPane.showMessageDialog(this, "Student ID " + id + " not found in database.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numbers for ID and Marks!", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String category = jComboBox2.getSelectedItem().toString().toLowerCase(); // id, name, etc.
    String keyword = JOptionPane.showInputDialog(this, "Enter " + category + " to search:");

    if (keyword == null || keyword.isEmpty()) return;

    try {
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        // We use "LIKE" so users can find "Osc" if they search for "Oscar"
        String sql = "SELECT * FROM students WHERE " + category + " LIKE ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, "%" + keyword + "%");
        
        java.sql.ResultSet rs = pst.executeQuery();

        jTextArea1.setText("ID\tName\tEmail\tCourse\tMarks\n");
        jTextArea1.append("--------------------------------------------------------------------------\n");
        
        boolean found = false;
        while (rs.next()) {
            found = true;
            jTextArea1.append(rs.getInt("id") + "\t" +
                               rs.getString("name") + "\t\t" +
                               rs.getString("email") + "\t\t\t" +
                               rs.getString("course") + "\t" +
                               rs.getInt("marks") + "\n");
        }
        
        if (!found) {
            JOptionPane.showMessageDialog(this, "No student found matching: " + keyword);
            loadStudents(); // Refresh to show all if none found
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Search Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        sortData("id");
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        sortData("name");
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        sortData("marks");
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
        filterByStatus(">= 50");
    }
    }

// Helper method to keep code clean
    private void filterByStatus(String criteria) {
// 1. Clear the old text and add a Header
    jTextArea1.setText("ID\tName\tEmail\tCourse\tMarks\n");
    jTextArea1.append("--------------------------------------------------------------------------\n");

    try {
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "SELECT * FROM students WHERE marks " + criteria;
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        boolean found = false;
        // 2. Loop through the filtered results
        while (rs.next()) {
            found = true;
            jTextArea1.append(rs.getInt("id") + "\t" +
                               rs.getString("name") + "\t" +
                               rs.getString("email") + "\t" +
                               rs.getString("course") + "\t" +
                               rs.getInt("marks") + "\n");
        }
        
        if (!found) {
            jTextArea1.append("\nNo students found matching this filter.");
        }

    } catch (Exception e) {
        // If 'this' gives an error here, use 'null'
        JOptionPane.showMessageDialog(null, "Filter Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()) {
        filterByStatus(">95");
    }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                                     
    try {
        // 1. Get data from fields
        //String idStr = jTextField3.getText().trim();
        String rawName = jTextField1.getText().trim();
        String email = jTextField2.getText().trim();
        String course = jComboBox1.getSelectedItem().toString();
        String marksStr = jTextField3.getText().trim();

        // 2. Validation: Check if empty
        if (rawName.isEmpty() || email.isEmpty() || marksStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return;
        }

        // 3. String Manipulation: Title Case (Lab Requirement)
        String formattedName = "";
        String[] words = rawName.split("\\s+");
        for (String word : words) {
            if (word.length() > 0) {
                formattedName += word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase() + " ";
            }
        }
        formattedName = formattedName.trim();

        // 4. Email Validation
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Invalid Email Format!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 5. Numeric Validation
        //int id = Integer.parseInt(idStr);
        int marks = Integer.parseInt(marksStr);
        if (marks < 0 || marks > 100) {
            JOptionPane.showMessageDialog(this, "Marks must be between 0 and 100");
            return;
        }

        // 6. Database Insertion
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "INSERT INTO students (name, email, course, marks) VALUES ( ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        //pst.setInt(1, id);
        pst.setString(1, formattedName);
        pst.setString(2, email);
        pst.setString(3, course);
        pst.setInt(4, marks);

        pst.executeUpdate();
        
        // 7. Success!
        JOptionPane.showMessageDialog(this, "Student Added Successfully: " + formattedName);
        
        // Refresh the table and clear fields
         loadStudents(); 
        clearFields();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID and Marks must be numbers!", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error (Check if ID already exists): " + e.getMessage());
    }
    }
    public void clearFields(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void sortData(String columnName) {
    jTextArea1.setText("ID\tName\tEmail\tCourse\tMarks\n");
    jTextArea1.append("--------------------------------------------------------------------------\n");
    try {
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        // Dynamic sorting based on which checkbox was clicked
        String sql = "SELECT * FROM students ORDER BY " + columnName + " ASC";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            jTextArea1.append(rs.getInt("id") + "\t" +
                               rs.getString("name") + "\t" +
                               rs.getString("email") + "\t" +
                               rs.getString("course") + "\t" +
                               rs.getInt("marks") + "\n");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Sort Error: " + e.getMessage());
    }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        clearFields();
        jTextArea1.setText(""); // Optional: also clear the preview area
        //loadStudents();
    }//GEN-LAST:event_jButton5ActionPerformed
    public void loadStudents() {
    // This clears the text area first so it doesn't just keep appending
    jTextArea1.setText("ID\tName\tEmail\tCourse\tMarks\n");
    jTextArea1.append("--------------------------------------------------------------------------\n");
    
    try {
        // Get connection from your Database class
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "SELECT * FROM students";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            // Pull data from columns
            int id = rs.getInt("id");
            String name = rs.getString("name");
            String email = rs.getString("email");
            String course = rs.getString("course");
            int marks = rs.getInt("marks");

            // Append to the TextArea
            jTextArea1.append(id + "\t" + name + "\t" + email + "\t" + course + "\t" + marks + "\n");
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error Loading Data: " + e.getMessage());
    }
}
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Exit Application?", "Confirm", JOptionPane.YES_NO_OPTION);
           if (confirm == JOptionPane.YES_OPTION) {
                System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        int minMarks = jSlider1.getValue();
    // Update the label next to the slider so user sees the number
    jLabel10.setText("Min Marks: " + minMarks); 
    
    // Filter the text area live!
    jTextArea1.setText("ID\tName\tEmail\tCourse\tMarks\n");
    jTextArea1.append("Showing students with marks >= " + minMarks + "\n");
    jTextArea1.append("--------------------------------------------------------------------------\n");
    
    try {
        java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
        String sql = "SELECT * FROM students WHERE marks >= ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, minMarks);
        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            jTextArea1.append(rs.getInt("id") + "\t" +
                               rs.getString("name") + "\t" +
                               rs.getString("email") + "\t" +
                               rs.getString("course") + "\t" +
                               rs.getInt("marks") + "\n");
        }
    } catch (Exception e) {
        // Silently handle or log
    }
    }//GEN-LAST:event_jSlider1StateChanged

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (jRadioButton2.isSelected()) {
        filterByStatus("< 50");
    }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        String idToDelete = JOptionPane.showInputDialog(this, "Enter Student ID to Delete:");
    
    if (idToDelete == null || idToDelete.isEmpty()) return;

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete ID: " + idToDelete + "?", "Confirm", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection con = com.sms.db.DatabaseConnection.getConnection();
            String sql = "DELETE FROM students WHERE id = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(idToDelete));
            
            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Student Deleted!");
                //loadStudents(); // Refresh display
            } else {
                JOptionPane.showMessageDialog(this, "ID not found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
